# Generated by Django 3.1.7 on 2021-03-29 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor', models.CharField(max_length=20)),
                ('User', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Price', models.FloatField()),
                ('Product_Details', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='image/download')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=10)),
                ('Phone_Number', models.IntegerField()),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.category')),
            ],
        ),
    ]
